package com.vmschmidt.travelapp.dataprovider;

import android.content.Context;
import android.graphics.drawable.Drawable;

import com.vmschmidt.travelapp.R;

import java.util.HashMap;

public class FlagProvider {

    public enum Flag{
        AD(R.drawable.ad),
        AE(R.drawable.ae),
        AF(R.drawable.af),
        AG(R.drawable.ag),
        AL(R.drawable.al),
        AM(R.drawable.am),
        AO(R.drawable.ao),
        AR(R.drawable.ar),
        AT(R.drawable.at),
        AU(R.drawable.au),
        AZ(R.drawable.az),
        BA(R.drawable.ba),
        BB(R.drawable.bb),
        BD(R.drawable.bd),
        BE(R.drawable.be),
        BF(R.drawable.bf),
        BG(R.drawable.bg),
        BH(R.drawable.bh),
        BI(R.drawable.bi),
        BJ(R.drawable.bj),
        BN(R.drawable.bn),
        BO(R.drawable.bo),
        BR(R.drawable.br),
        BS(R.drawable.bs),
        BT(R.drawable.bt),
        BW(R.drawable.bw),
        BY(R.drawable.by),
        BZ(R.drawable.bz),
        CA(R.drawable.ca),
        CD(R.drawable.cd),
        CF(R.drawable.cf),
        CG(R.drawable.cg),
        CH(R.drawable.ch),
        CI(R.drawable.ci),
        CL(R.drawable.cl),
        CM(R.drawable.cm),
        CN(R.drawable.cn),
        CO(R.drawable.co),
        CR(R.drawable.cr),
        CU(R.drawable.cu),
        CV(R.drawable.cv),
        CY(R.drawable.cy),
        CZ(R.drawable.cz),
        DE(R.drawable.de),
        DJ(R.drawable.dj),
        DK(R.drawable.dk),
        DM(R.drawable.dm),
        DO(R.drawable.dr),
        DZ(R.drawable.dz),
        EC(R.drawable.ec),
        EE(R.drawable.ee),
        EG(R.drawable.eg),
        EH(R.drawable.eh),
        ER(R.drawable.er),
        ES(R.drawable.es),
        ET(R.drawable.et),
        FI(R.drawable.fi),
        FJ(R.drawable.fj),
        FM(R.drawable.fm),
        FR(R.drawable.fr),
        GA(R.drawable.ga),
        GB(R.drawable.gb),
        GD(R.drawable.gd),
        GE(R.drawable.ge),
        GH(R.drawable.gh),
        GM(R.drawable.gm),
        GN(R.drawable.gn),
        GQ(R.drawable.gq),
        GR(R.drawable.gr),
        GT(R.drawable.gt),
        GW(R.drawable.gw),
        GY(R.drawable.gy),
        HN(R.drawable.hn),
        HR(R.drawable.hr),
        HT(R.drawable.ht),
        HU(R.drawable.hu),
        ID(R.drawable.id),
        IE(R.drawable.ie),
        IL(R.drawable.il),
        IN(R.drawable.in),
        IQ(R.drawable.iq),
        IR(R.drawable.ir),
        IS(R.drawable.is),
        IT(R.drawable.it),
        JM(R.drawable.jm),
        JO(R.drawable.jo),
        JP(R.drawable.jp),
        KE(R.drawable.ke),
        KG(R.drawable.kg),
        KH(R.drawable.kh),
        KI(R.drawable.ki),
        KM(R.drawable.km),
        KN(R.drawable.kn),
        KP(R.drawable.kp),
        KR(R.drawable.kr),
        KS(R.drawable.ks),
        KW(R.drawable.kw),
        KZ(R.drawable.kz),
        LA(R.drawable.la),
        LB(R.drawable.lb),
        LC(R.drawable.lc),
        LI(R.drawable.li),
        LK(R.drawable.lk),
        LR(R.drawable.lr),
        LS(R.drawable.ls),
        LT(R.drawable.lt),
        LU(R.drawable.lu),
        LV(R.drawable.lv),
        LY(R.drawable.ly),
        MA(R.drawable.ma),
        MC(R.drawable.mc),
        MD(R.drawable.md),
        ME(R.drawable.me),
        MG(R.drawable.mg),
        MH(R.drawable.mh),
        MK(R.drawable.mk),
        ML(R.drawable.ml),
        MM(R.drawable.mm),
        MN(R.drawable.mn),
        MR(R.drawable.mr),
        MT(R.drawable.mt),
        MU(R.drawable.mu),
        MV(R.drawable.mv),
        MW(R.drawable.mw),
        MX(R.drawable.mx),
        MY(R.drawable.my),
        MZ(R.drawable.mz),
        NA(R.drawable.na),
        NE(R.drawable.ne),
        NG(R.drawable.ng),
        NI(R.drawable.ni),
        NL(R.drawable.nl),
        NO(R.drawable.no),
        NP(R.drawable.np),
        NR(R.drawable.nr),
        NZ(R.drawable.nz),
        OM(R.drawable.om),
        PA(R.drawable.pa),
        PE(R.drawable.pe),
        PG(R.drawable.pg),
        PH(R.drawable.ph),
        PK(R.drawable.pk),
        PL(R.drawable.pl),
        PT(R.drawable.pt),
        PW(R.drawable.pw),
        PY(R.drawable.py),
        QA(R.drawable.qa),
        RO(R.drawable.ro),
        RS(R.drawable.rs),
        RU(R.drawable.ru),
        RW(R.drawable.rw),
        SA(R.drawable.sa),
        SB(R.drawable.sb),
        SC(R.drawable.sc),
        SD(R.drawable.sd),
        SE(R.drawable.se),
        SG(R.drawable.sg),
        SI(R.drawable.si),
        SK(R.drawable.sk),
        SL(R.drawable.sl),
        SM(R.drawable.sm),
        SN(R.drawable.sn),
        SO(R.drawable.so),
        SR(R.drawable.sr),
        ST(R.drawable.st),
        SV(R.drawable.sv),
        SY(R.drawable.sy),
        SZ(R.drawable.sz),
        TD(R.drawable.td),
        TG(R.drawable.tg),
        TH(R.drawable.th),
        TJ(R.drawable.tj),
        TL(R.drawable.tl),
        TM(R.drawable.tm),
        TN(R.drawable.tn),
        TO(R.drawable.to),
        TR(R.drawable.tr),
        TT(R.drawable.tt),
        TV(R.drawable.tv),
        TW(R.drawable.tw),
        TZ(R.drawable.tz),
        UA(R.drawable.ua),
        UG(R.drawable.ug),
        US(R.drawable.us),
        UY(R.drawable.uy),
        UZ(R.drawable.uz),
        VA(R.drawable.va),
        VC(R.drawable.vc),
        VE(R.drawable.ve),
        VN(R.drawable.vn),
        VU(R.drawable.vu),
        WS(R.drawable.ws),
        YE(R.drawable.ye),
        ZA(R.drawable.za),
        ZM(R.drawable.zm),
        ZW(R.drawable.zw);

        private final int flag;

        Flag(int flag){
            this.flag = flag;
        }

        int getFlag(){
            return this.flag;
        }
    }

    private static HashMap<Integer, Drawable> drawableCache = new HashMap<>();

    public static Drawable getDrawable(Context context, Flag flag){
        int resId = flag.getFlag();

        Drawable drawable = drawableCache.get(resId);
        if(drawable == null) {
            drawable = context.getDrawable(resId);
            drawableCache.put(resId, drawable);
        }
        return drawable;
    }
}
